### ISSUE TITLE
Error "Is a directory" when reopening existing store

### ISSUE THREAD

**Issue by pnewell** [mochidev/CodableDatastore#138]
I've been getting the following error any time I try to reinitialize a store that was previously created. Creating and using a store the first time always works, but if I try to reuse the same URL when rebuilding it always fails with this error:

> CodableDatastoreTest/CodableDatastoreTestApp.swift:18: Fatal error: 'try!' expression unexpectedly raised an error: Error Domain=NSCocoaErrorDomain Code=256 "The file “2023-07-13 20-58-15 29023E6541A4E39A.snapshot” couldn’t be opened." UserInfo={NSFilePath=/Users/_______/Library/Developer/CoreSimulator/Devices/B6EABA41-EBF0-46A4-8A33-0150DDA84DD2/data/Containers/Data/Application/505B0923-E569-441A-862C-351FA816B866/tmp/73B58D72-6462-4C31-B5B9-FF5DCF5C085F-19496-000005FDA764CEDA/Snapshots/2023/07-13/20-58/2023-07-13 20-58-15 29023E6541A4E39A.snapshot, NSUnderlyingError=0x600000c98660 {Error Domain=NSPOSIXErrorDomain Code=21 "Is a directory"}}

I even copied the `DiskPersistenceDatastoreTests` file and tried to run it twice with a static URL and get the same error

Example func that works the first time and successfully persists and then fails with above error when trying to build and run a second time
```swift
func write() {
        let url = FileManager.default.containerURL(forSecurityApplicationGroupIdentifier: "group.com.pnewelljr.CodableDatastoreTest")!.appending(path: "Store", directoryHint: .isDirectory)
        let persistence = try DiskPersistence(readWriteURL: url)
        try await persistence.createPersistenceIfNecessary()

        let datastore = Datastore.JSONStore(
            persistence: persistence,
            key: "test",
            version: Version.zero,
            migrations: [
                .zero: { data, decoder in
                    try decoder.decode(TestStruct.self, from: data)
                }
            ]
        )
       try await datastore.warm()
      
        
        try await datastore.persist(TestStruct(id: "3", value: "My name is Dimitri"))
        try await datastore.persist(TestStruct(id: "1", value: "Hello, World!"))
        try await datastore.persist(TestStruct(id: "2", value: "Twenty Three is Number One"))

        let count = try await datastore.count
}
```

**Comment by pnewell** [comment]
Same thing happens even when using defaultStore(). If I rebuild and try and run a second time and write to the store, on write attempt I get the error "Is a directory"

**Comment by pnewell** [comment]
I believe this line is the source of the issue:

```swift
            let data = try Data(contentsOf: snapshotURL)
```
/Persistence/Disk Persistence/Snapshot/Snapshot.swift (line 91)
https://github.com/mochidev/CodableDatastore/blob/b02fdbaca2048079e9f0027d89e6914b2be63137/Sources/CodableDatastore/Persistence/Disk%20Persistence/Snapshot/Snapshot.swift#L91C54-L91C54

**Comment by pnewell** [comment]
Here is a more full, simple example using the latest release (0.0.29). This example with just two files runs fine on first run, but fails on second run. I am using Xcode 15 beta 4 and have. tried the iOS simulator and building for Mac:

**Persistence.swift**
```swift
import CodableDatastore

final class Persistence {
  func write() async throws {
    enum Version: Int, CaseIterable {
      case zero
    }
    
    struct TestStruct: Codable, Identifiable {
      var id: String
      var value: String
    }
    
    let persistence = try DiskPersistence.defaultStore()
    
    let datastore = Datastore.JSONStore(
      persistence: persistence,
      key: "test",
      version: Version.zero,
      migrations: [
        .zero: { data, decoder in
          try decoder.decode(TestStruct.self, from: data)
        }
      ]
    )
    
    try await datastore.persist(TestStruct(id: "3", value: "My name is Dimitri"))
    try await datastore.persist(TestStruct(id: "1", value: "Hello, World!"))
    try await datastore.persist(TestStruct(id: "2", value: "Twenty Three is Number One"))
    
    let count = try await datastore.count
  }
}
```

**TestApp.swift**
```swift
import SwiftUI

@main
struct CodableDatastore29App: App {
  var store = Persistence()
  
    var body: some Scene {
        WindowGroup {
            EmptyView()
            .task {
              try! await store.write()
            }
        }
    }
}
````

**Comment by dimitribouniol** [comment]
Good catch! I'm embarrassed to say that I haven't written any tests that re-load the entire datastore from disk yet, so I fully expect you to find more issues 😅

**Comment by dimitribouniol** [comment]
Told you I'd find more 😅 https://github.com/mochidev/CodableDatastore/pull/152
